
<img src="img/viu_logo.png" width="200">

## 01MIAR - NumPy

![logo](img/python_logo.png)

*Ivan Fuertes*

# Sumario
- ndarray
- creacion y modificacion de ndarrays
- indexacion y slicing
- estadistica descriptiva
- filtrado de datos con where
- algebra lineal
- Valores aleatorios
- Leer y escribir NumPy ndarrays

# NumPy ndarray
- NumPy (__Num__ erical __Py__ thon) es la de facto librería estándar para análisis numérico en Python
- Estructura de datos multidimensional eficiente (escrita en C): ndarray
- Colección de funciones para álgebra lineal, estadística descriptiva
- Ayuda al procesamiento de datos (np.where)

In [2]:
#importar libreria
import numpy as np

In [3]:
shopping_list = [ ['onions','carrots','celery'], ['apples','oranges','grapes'] ] # 2D
array = np.array(shopping_list) # convertir una lista en una ndarray
print(array)
print(type(array))

[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


## Formas de crear ndarrays

In [4]:
print(np.array([100,10,1])) # array a partir de una lista
print(np.array(list(range(1,20))))
print(np.arange(2,10,2))    # array a partir de una secuencia(range) 1D

[100  10   1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2 4 6 8]


In [6]:
# Generar arrays con valores fijos
print(np.zeros(5))       # 1D
print(np.ones((2,2)))    # matrix 2x2
print(np.empty((2,2,2))) # matrix 2x2x2, no inicializados
print(np.full((5,2),-3)) # matrix 5x2
print(np.eye(3))         # matrix identity

[0. 0. 0. 0. 0.]
[[1. 1.]
 [1. 1.]]
[[[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 7.37145944e-321]
  [2.55896905e-307 2.44771196e-307]]]
[[-3 -3]
 [-3 -3]
 [-3 -3]
 [-3 -3]
 [-3 -3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Obtener información sobre ndarray

In [5]:
my_ndarray = np.array([2,71,0,19,71])
print(my_ndarray)

print(my_ndarray.argmax())    # índice del valor más alto
print(my_ndarray.argmin())    # índice del valor más bajo
print(my_ndarray.nonzero())   # retorna los índices de los elementos distintos a 0

[ 2 71  0 19 71]
1
2
(array([0, 1, 3, 4], dtype=int64),)


In [ ]:
my_ndarray = np.full((5,2),-3) # matrix 5x2
print(my_ndarray)

print(my_ndarray.size)        # número de elementos
print(my_ndarray.shape)       # dimensiones
print(my_ndarray.ndim)        # número de dimensiones

#### Redimensionar los datos

In [6]:
my_ndarray = np.array([[10, 71, 21, 19, 213, 412, 111, 98]])  # matrix 1x8
print(my_ndarray.shape)

# cambiar las dimensiones a 4x2
new_dims = my_ndarray.reshape(4, 2)
print(new_dims)

# cambiar las dimensiones a 2x4
new_dims = my_ndarray.reshape(2, 4) # qué sucede si utilizamos otros valores?
print(new_dims)

(1, 8)
[[ 10  71]
 [ 21  19]
 [213 412]
 [111  98]]
[[ 10  71  21  19]
 [213 412 111  98]]


In [7]:
# Cambiar ejes
new_dims = np.arange(16).reshape(4,4)

print(new_dims)
print(new_dims.swapaxes(0,1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [8]:
# reducir a 1D
new_dims = np.arange(9).reshape(3,3)

print(new_dims)
print(new_dims.flatten())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


## Manipulación de ndarrays

In [9]:
# ordenar
array1 = np.array([10,2,9,17])
array1.sort()
print(array1)

[ 2  9 10 17]


In [10]:
# Juntar dos arrays
a1 = [0,0,0,0,0,0]
a2 = [1,1,1,1,1,1]
print(np.hstack((a1,a2))) # una al lado de la otra
print(np.vstack((a1,a2))) # una encima de la otra

[0 0 0 0 0 0 1 1 1 1 1 1]
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]]


In [11]:
# dividir un array
array = np.arange(16).reshape(4,4)

print(array)
print(np.array_split(array,2)) # divide array en 2 partes iguales
print(np.array_split(array,3)) # divide array en 3 partes "iguales"

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [14]:
array = np.arange(16)
x,y = np.array_split(array,2)

print(x)
print(y)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]


In [15]:
# dividir un array
array = np.arange(16).reshape(4,4)

print(array)
print(np.array_split(array,[3], axis = 0)) # divide array, por la fila 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [27]:
array = np.arange(16).reshape(4,4)

print(array)
x,y,z=np.array_split(array,[0,3], axis = 0)
print(x)
print(y)
print(z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [28]:
array = np.arange(64).reshape(8,8)
print(array)
print(np.array_split(array, [1, 3, 6], axis = 0))  # divide array por la fila 1 y 3 y 6

print(np.array_split(array, [1, 3], axis = 1))  # divide array por la columna 1 y 3
# axis = n_dimensions - 1

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]]), array([[48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]
[array([[ 0],
       [ 8],
       [16],
       [24],
       [32],
       [40],
       [48],
       [56]]), array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50],
       [57, 58]]), array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23],
       [27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
      

# Índices y slicing
- De manera análoga a índices y slicing para listas

In [29]:
array = np.arange(10, 16)
print(array)
print(array[-1])    # acceso unidimensional
print(array[0:-1])  # slice

[10 11 12 13 14 15]
15
[10 11 12 13 14]


In [30]:
# bidimensional
array = np.arange(16).reshape(4,4)
print(array)
print(array[0, 1]) # fila, columna
print(array[0:2, 1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
1
[[1 2]
 [5 6]]


In [31]:
# multidimensional
array = np.arange(36).reshape(2,3,6)
print(array)
print(array[1, 2, 4])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
34


#### NumPy es row major

In [32]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3,order='C')  # by default, row major
print(row_major)

col_major = np.array([1, 2, 3, 4, 5, 6])
col_major = col_major.reshape(2,3,order='F')  # col major
print(col_major)

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


#### Slice

In [33]:
# se puede hacer slice por fila o columna
array = np.arange(9).reshape(3,3)
print(array)
print(array[:,0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 3 6]


In [34]:
# se puede hacer slice por fila o columna
array = np.arange(9).reshape(3,3)
print(array)
print(array[0,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


#### Diferencias entre índices y slicing en listas y ndarrays:
- ¡Retornan una referencia, no una copia!

In [35]:
# uso de slice en listas, retorna copia
lista = [0,1,2,3,4,5,6,7,8,9]
my_copy = lista[0:2]  # devuelve una copia
my_copy[0] = 222
print(lista)
print(my_copy)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[222, 1]


In [36]:
# slicing retorna una referencia en ndarrays
array = np.arange(10)
my_copy = array[2:5]  # devuelve una referencia
print(array)
print(my_copy)

my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[  0   1 222   3   4   5   6   7   8   9]
[222   3   4]


In [37]:
# copiar ndarrays
array = np.arange(10)
my_copy = array[2:5].copy()  # hay que hacer la copia explicitamente
my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[222   3   4]


- Permite asignar valores a un corte

In [38]:
array = np.arange(10).reshape(5,2)
array[:, 0] = -1
print(array)

[[-1  1]
 [-1  3]
 [-1  5]
 [-1  7]
 [-1  9]]


- Slicing condicionales (mask)

In [39]:
# slicing condicional
array = np.arange(-3,4)
print(array)

mask = array < 0

# mask = (array < 0) | (array > 0)
print(mask)

print(array[mask])

array[mask] = 0
print(array)

[-3 -2 -1  0  1  2  3]
[ True  True  True False False False False]
[-3 -2 -1]
[0 0 0 0 1 2 3]


In [40]:
# slicing condicional
array = np.arange(-3,4)
print(array)
mask = array % 2 == 0
print(mask)

array_positive = array[mask]  # devuelve una copia
print(array_positive)

array_positive[0] = -10
print(array)
print(array_positive)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-3 -2 -1  0  1  2  3]
[-10   0   2]


In [41]:
# slicing condicional
array = np.arange(-3,4)
mask = array % 2 == 0
print(mask)
print(array)
print(array[mask])

array[mask] = 10 # ??
print(array)

mask = array == 10
array[mask] = 0 # ??
print(array)

[False  True False  True False  True False]
[-3 -2 -1  0  1  2  3]
[-2  0  2]
[-3 10 -1 10  1 10  3]
[-3  0 -1  0  1  0  3]


# Funciones matemáticas
- Aplicar operaciones entre escalares y arrays o entre arrays

In [42]:
# listas y escalares
lista = [0,1,2,3]
lista *= 2
print(lista)

[0, 1, 2, 3, 0, 1, 2, 3]


In [43]:
# ndarray hace las operaciones sobre los elementos
array = np.ones(4) * 2
print(array)

array += 10
print(array)

[2. 2. 2. 2.]
[12. 12. 12. 12.]


In [44]:
# operaciones entre arrays es como operaciones entre matrices
array_1 = np.arange(1,17).reshape(4,4)
array_2 = np.arange(2,18).reshape(4,4)

print(array_1)
print(array_2)

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)
print(array_1 / array_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]
 [27 29 31 33]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
[[  2   6  12  20]
 [ 30  42  56  72]
 [ 90 110 132 156]
 [182 210 240 272]]
[[0.5        0.66666667 0.75       0.8       ]
 [0.83333333 0.85714286 0.875      0.88888889]
 [0.9        0.90909091 0.91666667 0.92307692]
 [0.92857143 0.93333333 0.9375     0.94117647]]


Si las arrays no tienen las mismas dimensiones --> [broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)
- Restricciones

## Operadores unarios y binarios

| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

In [45]:
# ejemplos de operadores
array = np.arange(5)
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [69]:
# ejemplos de operadores
array1 = np.ones(4)
array2 = np.array([0,-1,2,-3])


mask=np.greater(array1,array2)
print(mask)
print(array1[mask])



[ True  True False  True]
[1. 1. 1.]


# Estadística descriptiva
- Importante saber la naturaleza de los datos
- Valores máximos, mínimos, distribución, etc.

| Función | Descripción |
|:---------|:-----|
| *sum(arr)* | Suma de todos los elementos de *arr* |
| *mean(arr)* | Media aritmética de los elementos de *arr* |
| *std(arr)* | Desviación estándar de los elementos de *arr* |
| *cumsum(arr)* | Devuelve array con la suma acumulada de cada elementos con todos los anteriores |
| *cumprod(arr)* | Devuelve array con el producto acumulado de cada elementos con todos los anteriores |
| *min(arr), max(arr)* | Mínimo y máximo de *arr* |
| *any(arr)* | En array de tipo *bool*, retorna *True* si algún elemento es *True* |
| *all(arr)* | En array de tipo *bool*, retorna *True* si todos los elementos son *True* (o >0 en valores numéricos) |
| *unique(arr)* | Devuelve un array con valores únicos |
| *in1d(arr1, arr2)* | Devuelve un array con bool indicando si cada elemento de *arr1* está en *arr2* |
| *union1d(arr1, arr2)* | Devuelve la unión de ambos arrays |
| *intersect1d(arr1, arr2)* | Devuelve la intersección de ambos arrays |

In [ ]:
# sum != cumsum
array1 = np.arange(9)
print(array1)
print(array1.sum())
print(array1.cumsum())

In [ ]:
# any vs all
array1 = np.arange(10).reshape(2,5)
print(array1)
print(array1.any()) # any para saber si hay elementos True o valores > 0
print(array1.all()) # all para saber si TODOS los elementos son True o valores > 0

In [ ]:
# todas las funciones aceptan parametro 'axis' 
# 0 para columnas, 1 para filas, 2 para profundidad...
array1 = np.arange(10).reshape(2,5)
print(array1)
print(array1.all(axis=0))
print(array1.all(axis=1))
print(array1.all())

# Álgebra lineal
- numpy.linalg contiene funciones para álgebra lineal
- dot product, multiplicación de matrices, cálculo del determinante, factorizaciones...


| Función | Descripción |
|:---------|:-----|
| *dot(mat1, mat2)* | Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas |
| *matmul(mat1, mat2)* | Devuelve el producto entre dos matrices |
| *trace(mat1, mat2)* | Suma de las diagonales de ambas matrices |
| *det(mat)* | Devuelve el determinante de la matriz |
| *eig(mat)* | Computa los autovalores y autovectores de la matriz cuadrada *mat* |
| *inv(mat)* | Devuelve la inversa de la matriz |
| *qr(mat)* | Computa la factorización QR de *mat* |
| *solve(A, b)* | Resuelve el sistema lineal de ecuaciones *Ax = b* para *b*, cuando *A* es una matriz cuadrada |

In [63]:
A=np.ones(9).reshape(3,3)
A=A+1
B=np.identity(3)

print(A)
print(B)

c=np.dot(A,B)
print(c)

d=np.matmul(A,B)
print(d)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [64]:
A = np.arange(12).reshape(4,3)
B = np.arange(9).reshape(3,3)

print(np.matmul(A,B))
print(np.dot(A, B))
print(A @ B)

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]
 [ 96 126 156]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]
 [ 96 126 156]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]
 [ 96 126 156]]


In [65]:
# resolver sistema de ecuaciones
# 3x + 2y = 12
# x - 3y = 2
# Ax = b --> resolver para x

a = np.array([ [3,2],[1,-3] ])
b  = np.array([12,2])
x,y = np.linalg.solve(a,b)
print('x=' + str(x) + ', y=' + str(y))

x=3.6363636363636367, y=0.5454545454545454


In [ ]:
#matriz identidad
np.identity(4)

# Filtrado de datos
- Filtrar y modificar datos numéricos con np.where
- Retorna A o B en función de una condición en una array

In [66]:
prices = np.array([0.99, 14.49, 19.99, 20.99, 0.49])
# mask con los elementos menores de 1

mask = np.where(prices < 1, True, False)
print(mask)
print(prices[mask])

print(np.where(prices < 1, 1.0, prices))

[ True False False False  True]
[0.99 0.49]
[ 1.   14.49 19.99 20.99  1.  ]


In [70]:
# Se puede usar para sustituir datos fuera de rango
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)

clean_data = np.where(bank_transfers_values > 0, bank_transfers_values, 0)
print(clean_data)

[[ 0.99  0.   19.99]
 [20.99  0.   12.1 ]]


In [71]:
# limpiar NaN (sustitución)
data = [10, 12, -143, np.nan, 1, -3] # np.nan --> NotANumber, elemento especial
data_clean = np.where(np.isnan(data),0,data)
print(data_clean)

[  10.   12. -143.    0.    1.   -3.]


In [72]:
# np.where puede seleccionar elementos
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(3, 2)
credits = np.where(bank_transfers_values > 0) # array de índices para los que la condición es True

print(bank_transfers_values)
print(credits)
print(bank_transfers_values[credits]) # es igual que bank_transfers_values[bank_transfers_values > 0]

[[ 0.99 -1.49]
 [19.99 20.99]
 [-0.49 12.1 ]]
(array([0, 1, 1, 2], dtype=int64), array([0, 0, 1, 1], dtype=int64))
[ 0.99 19.99 20.99 12.1 ]


In [73]:
# valor de array dependiendo del valor en array referencia
rewards_default = np.arange(6)
rewards_upgrade = np.arange(6) * 10
daily_points = np.array([0, 0, 1, 6, 0, 2])

print(rewards_default)
print(rewards_upgrade)
print(daily_points)

final_rewards = np.where(daily_points > 1, rewards_upgrade, rewards_default)
print(final_rewards)

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[0 0 1 6 0 2]
[ 0  1  2 30  4 50]


# Números aleatorios
- Python módulo random

In [74]:
import random

print(random.random()) # número entre 0 y 1
print(random.randint(0,5)) # integral entre dos valores
print(random.uniform(0,5)) # real entre dos valores

0.2143140206118903
2
0.6550208717764344


In [75]:
# elegir un elemento al azar dentro de una colección
names = ['Marta','Anna','Vanesa']
random.choice(names)

'Anna'

## NumPy.random
- Generar fácilmente listas con valores aleatorios

In [76]:
print(np.random.rand()) # número entre 0 y 1
print(np.random.randint(0,5)) # integral entre dos valores 
print(np.random.randint(5, size=(2, 4))) # parametro 'size' para indicar las dimensiones)

0.6266736633722606
3
[[0 0 4 2]
 [1 2 0 1]]


In [ ]:
# array de elementos aleatorios (distribucion normal gaussiana, media 0, desviación 1)
print(np.random.randn(4,2))

In [ ]:
# otras distribuciones
print(np.random.binomial(n=5, p=0.3)) # 'n' intentos, 'p' probabilidad
print(np.random.uniform(low=0, high=10)) # distribución uniforme
print(np.random.poisson(lam=2, size=(2,2))) # 'lam' número de ocurrencias esperadas, retornar 'size' valores

## Random seed
- Números pseudo-aleatorios
- Ordenadores generan números a partir de ecuaciones
- Basadas en un número inicial (seed)
- Bueno para reproducibilidad de experimentos

In [83]:
i = 5
for _ in range(5):  
    np.random.seed(i) # misma semilla
    print(np.random.rand())

print()    
    
for i in range(5):
    np.random.seed(i) # diferentes semillas
    print(np.random.rand())

0.22199317108973948
0.22199317108973948
0.22199317108973948
0.22199317108973948
0.22199317108973948

0.5488135039273248
0.417022004702574
0.43599490214200376
0.5507979025745755
0.9670298390136767


# Escritura y lectura de ndarrays a archivos 
- Para futuro acceso
- Compartir datos con otros
- Formato *.npy

In [ ]:
# escribir a archivo
import os
ruta = os.path.join("res" ,"o_values_array.npy")
values = np.random.randint(9, size=(3,3))

np.save(ruta, values)
print(values)

In [ ]:
# leer de archivo
old_values = np.load(ruta)
print(old_values)

In [ ]:
# escribir y cargar múltiples arrays
ruta = os.path.join("res" ,"o_array_group.npz")
values1 = np.random.randint(9,size=(3,3))
values2 = np.random.randint(4,size=(2,2))
values3 = np.random.randint(16,size=(4,4))
np.savez(ruta,values1,values2,values3) # añade la extensión .npz   

In [ ]:
# leer los archivos (retorna un lista con las arrays)
npzfile = np.load(ruta)
print(type(npzfile.files))

for key in npzfile.files: # array.files contiene el nombre de las arrays (arr_0, arr_1...)
     print(npzfile[key])

### ¿Por qué molestarse con .npy?
- Bases de datos suelen estar en CSV o txt, que requieren lectura con streams (parsing)
- ¿Para qué escribir los datos de nuevo?

In [ ]:
ruta_csv = os.path.join("res" ,"fdata.csv")
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)
print(data_array)

ruta_npy = os.path.join("res" ,"o_fdata.npy")
np.save(ruta_npy, data_array)

In [ ]:
%%timeit # magic function jupyter
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data,  dtype = np.int8).reshape(1000,1000)

In [ ]:
%%timeit
data = np.load(ruta_npy)

# Ejercicios
- Ejercicios para practicar NumPy: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb
- Con pistas: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_hints.md
- Soluciones en: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md

### velocidad + simplicidad vs memoria

- __No mires las soluciones desde el principio__. Intenta resolverlos por tu cuenta
- No hemos dado todo ¡Investiga!
- Comentar resultados en el foro

1. Import the numpy package under the name np (★☆☆)


In [84]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)





In [87]:
print(np.version)

<module 'numpy.version' from 'c:\\Users\\acasa\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


3. Create a null vector of size 10 (★☆☆)


In [89]:
a = np.zeros(10)

4. How to find the memory size of any array (★☆☆)


In [95]:
a.size*a.itemsize

80

5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [91]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x000001C9D61888B0>, toplevel='numpy')>

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [94]:
a=np.zeros(10)
a[5]=1

print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [99]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)


In [107]:
a=np.arange(29)
a=a[::-1]
print(a)

[28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5
  4  3  2  1  0]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [110]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


In [116]:
a=np.array([1,2,0,0,4,0])
mask= a>0
print(mask)
print(a.nonzero())



[ True  True False False  True False]
(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix (★☆☆)


In [117]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)


In [127]:

a=np.random.random(27).reshape(3,3,3)

b=np.random.random((3,3,3))
print(a)

print(b)

[[[0.55192644 0.18096484 0.40959139]
  [0.76288179 0.99079682 0.07365237]
  [0.13475261 0.74004473 0.83378137]]

 [[0.08877286 0.82941795 0.78673231]
  [0.68822127 0.33992642 0.44454066]
  [0.36633614 0.84046606 0.32832214]]

 [[0.32257498 0.93529086 0.91998735]
  [0.96867413 0.80754895 0.08691562]
  [0.09091055 0.55708208 0.85618377]]]
[[[0.88419786 0.63684867 0.95580459]
  [0.1518856  0.22158093 0.33249517]
  [0.25680492 0.31220503 0.11844552]]

 [[0.37534014 0.029774   0.53778167]
  [0.94582829 0.44512519 0.62415324]
  [0.61181235 0.93337917 0.73451905]]

 [[0.82482093 0.33584941 0.90746465]
  [0.18520923 0.40798227 0.73745197]
  [0.33345638 0.88613423 0.86065586]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [130]:
a=np.random.random((10,10))
print(a.min())
print(a.max())

0.011921328044363078
0.9839657157628715


14. Create a random vector of size 30 and find the mean value (★☆☆)


In [132]:
a=np.random.random(30)
a.mean()

0.5326846835084419

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [145]:
a=np.ones((10,10))
print(a)

a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? (★☆☆)


17. What is the result of the following expression? (★☆☆)


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


22. Normalize a 5x5 random matrix (★☆☆)


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
