# Examen Demo

In [2]:
# Your imports HERE !!!!
import numpy as np

## 01
- La serie de Fibonacci es una sucesión de números, en la cual cada número es la suma de los dos anteriores. Los dos primeros son siempre 0 y 1.
  - $F_0 = 0$
  - $F_1 = 1$
  - $F_n = F_{n-1} + F_{n-2}$
- Crear una serie de Fibonacci hasta un número *n* usando una función lambda.

In [3]:
expected_fibo_serie = [0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597]
fibo_serie = fibonacci_lambda(len(expected_fibo_serie))  # This calls your lambda function fibonacci_lambda
assert(expected_fibo_serie == fibo_serie)  # This will fail if the serie is not correct

NameError: name 'fibonacci_lambda' is not defined

In [ ]:
# Your solution HERE !!!!
from functools import reduce # necesario para reduce


#expected_fibo_serie = lambda n:reduce(lambda x,y: x+y,[0,1]),n+1
fibonacci_lambda= lambda n: reduce(lambda x,y:x+[x[-1]+x[-2]], range(n-2),[0,1])

print(fibonacci_lambda(10))




[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


## 02
- Crear una función que reciba un array de NumPy y devuelva otro en el cual estén marcados como True los elementos duplicados (a partir de la segunda ocurrencia), y como False los no repetidos o las primeras ocurrencias de los duplicados.

In [ ]:
numbers = np.array([4, 4, 4, 3, 8, 1, 9, 6, 1, 5, 9, 4, 0, 2])
expected_output = np.array([False, True, True, False, False, False, False, False, True, False, True, True, False, False])
output = find_duplicates(numbers)   # This calls your function find_duplicates
assert(np.array_equal(expected_output, output))  # This will fail if the result is not as expected

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
[12  5 13  3  0  9  7  4  6]


In [9]:
# Your solution HERE !!!!

def find_duplicates(array):
    a=np.full(array.size,True)
    _,mask= np.unique(array, return_index=True)
    
    print(_)
    print(mask)
    a[mask]=False
    return a


numbers = np.array([4, 4, 4, 3, 8, 1, 9, 6, 1, 5, 9, 4, 0, 2])

print(find_duplicates(numbers))

[0 1 2 3 4 5 6 8 9]
[12  5 13  3  0  9  7  4  6]
[False  True  True False False False False False  True False  True  True
 False False]


In [12]:
def find_duplicates(array):
    a=np.full(array.size,True)
    _,mask= np.unique(array, return_index=True)    
    print(_)
    print(mask)
    a[mask]=False
    return a

numbers = np.array([4, 4, 4, 3, 8, 1, 9, 6, 1, 5, 9, 4, 0, 2])

print(find_duplicates(numbers))

[0 1 2 3 4 5 6 8 9]
[12  5 13  3  0  9  7  4  6]
[False  True  True False False False False False  True False  True  True
 False False]


## 03
- Resolución de dos sistemas de ecuaciones
    - $ A : \begin{cases} -9x +  4y = 20 \\ -7y + 16x = 80                         \end{cases}$
    
    - $ B : \begin{cases} x - 2y + 3z = 7 \\ 2x + y + z = 4 \\ -3x + 2y -2z = -10 \end{cases}$
- Verifica por código los resultados

In [28]:
a = np.array([[1,-2,3],[2,1,1],[-3,2,-2]])
b = np.array([7,4,-10])

x,y,z = np.linalg.solve(a,b)

j= x -2*y + 3*z
j

7.0

In [20]:
# Your solution HERE !!!!

import numpy as np

a = np.array([[-9,4],[16,-7]])
b= np.array([20,80])

x, y = np.linalg.solve(a,b)


z=(-9*x) + (4*y)
z=(-9*x) + (4*y)
z

20.0

## 04
- Crear un objeto Series con 10 elementos, que contenga más de un tipo básico, con índices de tipo string
- Demuestra que los datos con índices posicionales son los mismos que los obtenidos con índices semánticos, seleccionando a través de slicing, al menos 4 elementos de la serie anterior

In [36]:
# Your solution HERE !!!!

#import pandas as pd

series = pd.Series([1,2,3,4,5,6,'X',True,'Y',10], index=list('abcdefghij'))

series

a       1
b       2
c       3
d       4
e       5
f       6
g       X
h    True
i       Y
j      10
dtype: object

In [46]:
a=series[:4]
b=series[:'d']
b
assert(np.array_equal(a,b))

## 05
- Crear un DataFrame de dimensiones 10x10, con números aleatorios en el rango `[0,20]`
- Reemplazar todos aquellos elementos menores de 5 por NaN
- Averiguar cuantos elementos tienen Nan por fila

In [61]:
# Your solution HERE !!!!
from random import shuffle

df = pd.DataFrame(np.random.randint(20, size=(10,10)))
display(df)
df[df==5]=np.nan
display(df)
df.isna().sum(axis=1)

0   1   2   3   4   5   6   7   8   9
0  13   2   7   1  19  10  16   4   1  11
1  11   4  11   0   3  12  11   1  12  15
2   4   9   8   0  14  11   9   0  12   8
3   1   4   1   2  14  13   3   8  14  13
4   2   3   8  13   3  15   1   1  18  11
5   3  14   6   7   9  13   3   3  12  13
6  14   1  10  12  16  19  19  12  14   7
7  10   6   6   4   5   6  11  11  14  13
8  13  11  16  12   0   6  18  13   4   9
9   4  14   6  19  14   8  17   7  18  10

0   1   2   3     4   5   6   7   8   9
0  13   2   7   1  19.0  10  16   4   1  11
1  11   4  11   0   3.0  12  11   1  12  15
2   4   9   8   0  14.0  11   9   0  12   8
3   1   4   1   2  14.0  13   3   8  14  13
4   2   3   8  13   3.0  15   1   1  18  11
5   3  14   6   7   9.0  13   3   3  12  13
6  14   1  10  12  16.0  19  19  12  14   7
7  10   6   6   4   NaN   6  11  11  14  13
8  13  11  16  12   0.0   6  18  13   4   9
9   4  14   6  19  14.0   8  17   7  18  10

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    1
8    0
9    0
dtype: int64

## 06
- Dada una lista de elementos, crea una función que devuelva un dataframe sin los elementos duplicados

In [67]:
serie = ['a','b','c','a','c','a','g']
expected_output = pd.DataFrame(['a','b','c','g'])
output = remove_duplicates(serie)   # This will call tour function remove_duplicates
assert(expected_output.equals(output))  # This will fail if the result is not as expected

In [66]:
# Your solution HERE !!!!

def remove_duplicates(serie):
    return pd.DataFrame(np.unique(serie))


remove_duplicates(serie)

0
0  a
1  b
2  c
3  g

## 07
- La serie de Fibonacci es una sucesión de números, en la cual cada número es la suma de los dos anteriores. Los dos primeros son siempre 0 y 1.
  - $F_0 = 0$
  - $F_1 = 1$
  - $F_n = F_{n-1} + F_{n-2}$
- Crear un generador infinito de números de Fibonacci.

In [3]:
fibo = [0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597]
g = fibonacci_generator()  # This calls tour function fibonacci_generator
expected_output = [next(g) for n in range(len(fibo))]
assert(fibo == expected_output)  # This will fail if the output is not as expected

In [2]:
# Your solution HERE !!!!
def fibonacci_generator():
    init = [0,1]    
    while True:        
        init.append(init[-1]+init[-2])
        yield init[-3]
        #init[-1]


In [206]:
# Your solution HERE !!!!
def fibonacci_generator():
    init = [0,1]    
    while True:
        yield init[-2]
        init.append(sum(init[-2:]))


In [203]:
init = [0,1,1,2,3,5] 
sum(init[-2:])

8

In [220]:
next(g)

4181

In [218]:

g = fibonacci_generator()
expected_output = [next(g) for n in range(len(fibo))]

print(expected_output)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597]


## 08
- Crear una función que reciba una Serie de Pandas y devuelva esa misma serie, reemplazando los espacios en blanco por el carácter menos frecuente en dicha serie.

In [201]:
serie = pd.Series(list('bba cabc fdabba aacbbfe'))
expected_output = pd.Series(list('bbaecabcefdabbaeaacbbfe'))
output = clean_whitespace_replace(serie)  # This calls your function clean_whitespace_replace
assert(expected_output.equals(output))  # This will fail if result is not as expected

In [199]:
# Your solution HERE !!!!

def clean_whitespace_replace(serie):
     serie[serie==' '] =serie.value_counts().index[-1]
     return serie

In [200]:
serie = pd.Series(list('bba cabc fdabba aacbbfe'))
print(clean_whitespace_replace(serie))

0     b
1     b
2     a
3     e
4     c
5     a
6     b
7     c
8     e
9     f
10    d
11    a
12    b
13    b
14    a
15    e
16    a
17    a
18    c
19    b
20    b
21    f
22    e
dtype: object
