<img src="../img/viu_logo.png" width="200">

## 01MIAR - Actividad Whitepapers



Autor: *EFRAIM ALBERTO CASAS*

## Artículo 01

### The NumPy array: a structure for efficient numerical computation

Van Der Walt, S., Colbert, S. C., &amp; Varoquaux, G. (2011). The NumPy array: A
structure for efficient numerical computation. Computing in Science and
Engineering, 13(2), 22-30. https://doi.org/10.1109/MCSE.2011.37

https://www.researchgate.net/publication/224223550_The_NumPy_Array_A_Structure_for_Efficient_Numerical_Computation

En este artículo se presenta la estructura *ndarray* de NumPy, y se hace un estudio sobre su uso y cómo mejora el rendimiento de ciertas operaciones matemáticas para la computación numérica.

Se hace una breve introducción al *Broadcasting* como técnica que usa NumPy para realizar operaciones artiméticas sobre dos o más arrays con distintas dimensiones. 

- Actividad 01.01 - Ampliar dicha explicación, aportando posibles restricciones o limitaciones a dicho sistema y ejemplos propios de los casos de uso.

También se introduce el trabajo con ficheros usando memoria mapeada.

- Actividad 01.02 - Verificar la eficacia y mejora posible de rendimiento del uso de memoria mapeada sobre ndarrays de tamaños grandes.

### Solución

#### Actividad 01

Broadcasting es la propiedad de Numpy que permite realizar operaciones aritmeticas con arrays (matrices) de diferentes formas, esto junto con la propiedad de vectorización son las que brindan a Numpy gran parte de su versatilidad y potencia.  

Cuando Numpy se encuentra con arrays que no tienen la misma forma y requiere hacer operaciones conjuntas sobre estos, aplica las siguentes regras

1. Primera Regla

Si dos arrays no tienen el mismo número de dimensiones, entonces se añadirá una dimensióm al principio del array con menor rango hasta que estos coincidan. 



In [13]:
#Ejemplo regla 1

import numpy as np

A = np.array([[ [ 0,10]]])

B= np.array([5])

print(A)
print(B)

print(A+B)




[[[ 0 10]]]
[5]
[[[ 5 15]]]


In [14]:
#otro ejemplo regla 1

print (2+A)

[[[ 2 12]]]


2. Segunda Regla

SI un array tien un 1 en  alguna dimensión en particular actuará como si tuviera la longitud del array con mayor logitud en aquella dimensión. Esto implica que el valor en esta dimensión se repetirá hasta coincidir con la longitud.

In [38]:
#Ejemplo Regla2

A=np.arange(3) #Matriz 1x3
print(A)

B=np.array([5]) #Matriz 1x1
print(B)

print(A+B)


[0 1 2]
[5]
[5 6 7]


In [39]:
A=np.ones((4,4)) #Matriz 4x4
print(A)
B=np.arange(4) #Matriz 1x4
print(B)

print(A+B)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [45]:
#Ejemplo regla 3
A=np.arange(1,11).reshape(1,10)
print(A)
B=np.arange(1,11).reshape(10,1)
print(B)
print(A+B)

[[ 1  2  3  4  5  6  7  8  9 10]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


3. Tercera Regla

Si depues de aplicar las reglas 1 y 2 las dimensiones de los arrays siguen sin coincidir, entonces la operación no se puede realizar.

In [37]:
A=np.arange(6).reshape(2,3) #Matriz 2x3
B= B=np.array([1,10]) #Matriz 1x2

print(A)
print(B)
print(A+B)


[[0 1 2]
 [3 4 5]]
[ 1 10]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [25]:
#la operación se podría dar si se hace un reshape de A

print(A.reshape(3,2)+B)

[[ 1 11]
 [ 3 13]
 [ 5 15]]


### Actividad 02

Rendimiento del uso de memoria mapeada sobre ndarrays de tamaños grandes


Ejemplo 1, 
Muesta como se hace el reshape de una matriz de 1'000.000 elementos. Para este caso Numpy conserva los mismos elementos en memoria y hace un cambio de la propiedad Strides. 

In [77]:
A = np.arange(1000000)
print(f"Shape:  {A.shape}")
print(f"Estrides: {A.strides}")

A.shape=(1000,1000)
print(f"Shape:  {A.shape}")
print(f"Estrides: {A.strides}")

Shape:  (1000000,)
Estrides: (4,)
Shape:  (1000, 1000)
Estrides: (4000, 4)


Como podemos ver la operación solo tarda decimas de segundos, para redifinir la columna de un millón de elementos.


Estrides: (4000, 4)

Lo que Numpy hace internamente es modificar la propiedad strides: Cuando se hace el reshape, la propiedad strides cambia a (4000,4) esto quiere decir que para pasar a la siguiente file requiere desplazarse en memoria 4000 Bytes, mientras que para ir a la siguiente columna solo requiere desplazarse 4 Bytes.




Ejemplo cambiando la forma de la matriz a tres dimensiones.



In [78]:

A.shape=(10,100,1000)
print(f"Shape:  {A.shape}")
print(f"Estrides: {A.strides}")


Shape:  (10, 100, 1000)
Estrides: (400000, 4000, 4)


Conclusión:

En cada uno de estos casos los array apuntan a la misma dirección en memoria, la diferencia de cada uno de los arreglos radica en la forma como se interpretan los datos basados en la propiedades, shape y strides.

#### Modificando el tipo de dato

Tipo de datos
En el anterior ejemplo veiamos que el deplazamiento entre cada columna estaba dado por 4 Bytes, esto sucede porque el tipo de dato es un enterod de 32 bits, para almacenar 32 bites se requieren 4 Bytes.



In [79]:
print(f"Tipo Dato: {A.dtype}")

Tipo Dato: int32


In [89]:
#Cambiemos el tipo de dato
B= np.empty((1000,1000))
B.dtype=np.dtype('short')


print(f"Tipo Dato: {B.dtype}")

print(f"Estrides: {B.strides}")


Tipo Dato: int16
Estrides: (8000, 2)


Para este caso el desplazamiento por columnas solo es de 2 Bytes porque el tipo short corresponde a 16 bites, los cuales pueden ser representados por 2 Bytes.

## Artículo 02

### Data Structures for Statistical Computing in Python

McKinney, W. (2010). Data Structures for Statistical Computing in Python.
Proceedings of the 9th Python in Science Conference, December, 56-61.
https://doi.org/10.25080/majora-92bf1922-00a

https://www.researchgate.net/publication/265001241_Data_Structures_for_Statistical_Computing_in_Python

En este segundo artículo el creador de *pandas* introduce dicha librería en comparación con las estructuras nativas de R.

- Actividad 02.01 - Desarrollar una opinión razonada del estado actual de las herramientas de análisis de datos estadísticos en contraposición a como se muestran en el artículo, R vs Python vs SQL vs Others...

### Solución


Desde el lanzamiento de Pandas y tal como vaticinaba Wes McKinney, autor del artículo y a su también creador de esta librería, esta se ha convertido no solo en una herramienta robusta para la computación estadística y el análisis de datos sino que casi en un estándar de la industria de ciencia de datos y machine learning.


Las principales características que le han permitido a Pandas ser una de las herramientas preferidas a la hora de realizar análisis de datos, han sido, la facilidad de implementar funciones cotidianas para el tratamiento de datos:

- Alinear Datos.
- Depuración y operaciones con datos faltantes.
- Combinación de Datasets (join).
- Agrupamiento de Datos por variables categóricas.
- Pivoteo de Datos.
- Facilidad en implementación de modelos estadísticos. 
- Manejo de Fechas.

Adicionalmente de la fácil interacción con otras librerías como son Matplotlib, SciPy e innumerables más que tienen como soporte para el manejo de datos a Pandas.

No solo la facilidad y su sintaxis amigable han sido la clave del éxito de Pandas sino la velocidad de cómputo a la hora de procesar datos. Hoy en día lo vemos como algo de nuestro diario vivir, pero hace 10 años no era algo común. Esta doble capacidad que tiene Pandas ha permitido a la ciencia de Datos da un gran avance en términos de productividad. 


### Pandas vs SQL

SQL (Structured Query Language) fue presupuesto en el año 1970 en el laboratorio de investigación de IBM en California y durante muchos años ha sido la fuente primaria para análisis de datos estructurados en Bases de Datos, tanto relacionales RDBMS y OLAP.

Pandas aunque inicialmente inspirándose en R también ha tratado de solventar las capacidade de consulta del lenguaje SQL, aunque con paradigma diferente en varios aspectos.


A continuación presentaré ejemplos de uso entre ambos lenguajes


*Describir un set de datos o tabla*

In [ ]:
DESC empleados;

In [ ]:

import pandas as pd
empleados = pd.read_csv("/content/empleados.csv")

empleados.dtypes

*Selección de columnas*


In [ ]:
SELECT CustomerId, Geography FROM CHURN;

In [ ]:
empleados[['CustomerId', 'Geography']]

*Filtros* 

Selección de filas por algún o algunos criterios en particular 

In [ ]:
SELECT CustomerId, Geography FROM CHURN
WHERE Geography = 'France'
LIMIT 5;

In [ ]:
empleados[empleados.Geography == 'France'][['CustomerId','Geography']][:5]

*Valores únicos*

In [ ]:
SELECT DISTINCT Geography FROM CHURN;

In [ ]:
empleados.Geography.unique()

*cantidad de valores únicos*

In [ ]:
SELECT COUNT(DISTINCT Geography) FROM CHURN;

In [ ]:
empleados.Geography.nunique()

*Agrupacion de datos por categoría, funciones de agregación y ordenamiento*

In [ ]:
SELECT Geography, AVG(Age) AS 'Average Age' 
FROM CHURN
GROUP BY Geography
ORDER BY Age;

In [ ]:
empleados[['Geography','Age']].groupby('Geography').mean()\
.sort_values(by='Age', ascending=False)

#### Conclusión

En la actualidad Pandas y SQL soportan muchas funcionalidades replicables mutuamente y en mi opinión personal no son herramientas excluyentes sino complementarias y las condiciones de cada caso de uso son las que determinan cual se acompla más a la solución  o también la posibilidad de utilizar ambas. 

Pandas como principal ventaja tien la posibilidad de uso de una gran cantidad de librerías las cuales facilitan el análisis de datos y donde ir uno o varios pasos más allá de describir la información es imperativo, ejemplo de estos son: modelos estadísticos, regresiones lineales, creación de modelo de machine learning entre muchos otros casos.

SQL tiene como ventaja la opción de acceder a fuentes primarias de datos como bodegas de datos, creación de dashboards y funciones que utilizan datos en caliente. Las bases de Olap están optimizadas para almacenamiento y procesamiento de grandes cantidades de datos y los niveles de disponibilidad son altos.

Muchas soluciones y en especial en ambientes corporativos pueden utilizar ambas tecnologías de forma complementaría y armónica, permitiendo a las rutinas creadas dentro de python cargar Pandas dataframes a partir de datos en tiempo real que estén en bases de datos y darle un procesamiento previo -si es necesario- mediante sentencias SQL para tener los datos mejor procesados, ejemplo join, filtros, cast entre un mar de posibilidades.

Actualmente también he utilizado una solución que me ha parecido muy potente:  Mediantes sentencias SQL acceder a modelos de machine learning creados y entrenados en AWS Sage Maker con el apoyo de Pandas. Esta solución utilizando AWS redshift ML. Y permite poder validar modelos en tiempo real con toda la información disponible en una bodega de datos, sin tener que hacer cargas a otros sistemas para poder ser evaluada de forma muy inmediata.
